### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by omar-dulaimi** [catalinmiron/awesome-prisma#52]
Hello,

I have a few PRs that have been stuck for a while now. So, I was wondering if this project is active at all.

If it's possible, I would like to be a maintainer, so I could help with it.

Otherwise, I would have to create a new awesome-prisma list, and there would be a big focus on it being active, so that it would be welcoming to new contributions from the prisma community.

Please let me know what you think.

Thank you!

**Comment by catalinmiron** [comment]
Hi @omar-dulaimi, yes, this repository its active. 

> Otherwise, I would have to create a new awesome-prisma list

Sure, go for it

**Comment by omar-dulaimi** [comment]
This is not the point man. There's no need to create a new one if it's active.

Please accept my PRs. If there's something I should edit, I would appreciate it if you gave me any feedback.
